[package]
name = "file_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempdir = "0.3.7"
tempfile = "3.14.0"

[dev-dependencies]
tempfile = "3.14.0"
