[package]
name = "day-4"
version = "0.1.0"
edition = "2024"

[dependencies]
file_reader = { workspace = true }
array_utils = { workspace = true }
macro_utils = { workspace = true }
itertools = { workspace = true }